type: edu
custom_name: "Exercise: Inventory"
files:
  - name: src/inventory.ads
    visible: true
  - name: src/inventory.adb
    visible: true
    placeholders:
      - offset: 91
        length: 228
        placeholder_text: |2-
                --  Return the name as it should be printed!
                return "";
      - offset: 434
        length: 320
        placeholder_text: |2-
                --  Build the item from its three parts!
                return (Ballpoint_Pen, 0, 0.0);
      - offset: 832
        length: 54
        placeholder_text: |2-
                --  Add this item's total value to Assets!
                null;
  - name: tests/test_inventory.adb
    visible: false
